[package]
name = "wg-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.26"
crossterm = "0.27"
qrcodegen = "1.8"

serde = { version = "1.0", features = ["derive"] }
toml = "0.8"  # or latest
anyhow = "1.0"

ring = "0.16"
base64 = "0.13"